obj-$(CONFIG_MALI_VER_R3P2_REL2) += r3p2_rel2/
obj-$(CONFIG_MALI_VER_R4P0_REL0) += r4p0_rel0/
obj-$(CONFIG_MALI400_UMP)        += ump_r3p2/

EXTRA_CFLAGS += -Idrivers/gpu/arm/mali400 -O3 -ffast-math -fgcse-lm -fgcse-sm -fsched-spec-load -fforce-addr -fsingle-precision-constant -mcpu=cortex-a7 -mtune=cortex-a7 -marm -mfpu=neon-vfpv4
